# This is a basic workflow to help you get started with Actions

name: Dev server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a single command using the runners shell
      - name: Executing Dev remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git add .
            git stash
            git checkout dev
            git pull origin dev
            php artisan down
            composer install
            php artisan migrate
            php artisan up
            echo "End"

      #      - name: Notify slack Deployment Suceded
      #        if: success()
      #        env:
      #          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #        uses: voxmedia/github-action-slack-notify-build@v1
      #        with:
      #          channel: deploys
      #          status: SUCCESS
      #          color: good

      - name: Notify slack Deployment Failed
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deploys
          status: FAILED
          color: danger

